---
struct:
  id_underlying: uint8_t
  default_endianness: little
  # unused features
  stream: false
  unit_test: false

clang_format: clang-format-19

enum:
  id_underlying: uint8_t
  use_map: false
  # unused features
  unit_test: false
